#latest mariadb & mysql version
FROM mariadb:latest

COPY my.cnf /etc/mysql/conf.d/
RUN chmod 644 /etc/mysql/conf.d/my.cnf

COPY ./scripts/ /docker-entrypoint-initdb.d/

# Install additional packages (if needed)
RUN apt-get update && apt-get install -y mytop percona-toolkit

ENV TZ=America/Edmonton

HEALTHCHECK CMD mysqladmin ping -h localhost
