version: '3'
services:
  www:
    container_name: phpapache
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: a3db
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    ports:
      - "3306:3306"
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"
    secrets:
      - db_password
      - db_root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

secrets:
  db_password:
    file: password.txt
  db_root_password:
    file: password.txt

volumes:
  mysql_data: {}
