services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: a3db
      MYSQL_USER: admin
      MYSQL_PASSWORD: /run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  mariadb_data: {}