version: '3'
services:
  www:
    container_name: phpapache
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=a3db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  mysql_data: {}